image: datepollsystems/android-gradle:latest

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

stages:
  - build
  - test

lintDebug:
  stage: build
  script:
    - ./gradlew build

debugTests:
  stage: test
  script:
    - ./gradlew test

