image: datepollsystems/android-gradle:latest

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

stages:
  - clean
  - build
  - test

cleanup:
  stage: clean
  script:
    - gradle clean

lintDebug:
  stage: build
  script:
    - gradle -Pci --console=plain :app:lintDebug -PbuildDir=lint

assembleDebug:
  stage: build
  script:
    - gradle assembleDebug

debugTests:
  stage: test
  script:
    - gradle -Pci --console=plain :app:testDebug
